source_to_site calculation (inc. rrup) as a separate step to compute empirical
ucgmsim/Empirical_Engine pull request #113
Opened 2024-08-02 04:54 UTC by sungeunbae

Previously, source_to_site calculation was done on-the-fly as a part of empirical calculation.

However, there was a need for having a step to add uncertainty to the rrup values before empirical calculation, and the current workflow was too tightly integrated. 

In this PR, the source_to_site calculation has been taken out a separate step. 

The new collect_sites_info script takes multiple input files, .ll, .vs30, .z and srf (or .nhm), and generates a single CSV file that also includes rrup, rjb, rx,ry.

This single CSV file is now a required input for the caclulate_empirical.py, making its command interface simplified.

If a researcher wishes to add perturbation to any of these values (eg. vs30, rrup, z etc), he/she can process the CSV file and feed the updated CSV file to caclulate_empirical.py

Usage:
```
(ringo310) seb56@c015kr:~/Empirical_Engine$ python ~/Empirical_Engine/empirical/scripts/collect_sites_info.py --help
                                                                                                                                      
 Usage: collect_sites_info.py [OPTIONS] SOURCE_FFP LL_FFP VS30_FFP Z_FFP                                                              
                                                                                                                                      
 Calculate source-site distances for stations in ll_ffp and put them alongside vs30 and z values into a single CSV file. Can work     
 either with SRF or NHM for a valid fault                                                                                             
                                                                                                                                      
╭─ Arguments ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ *    source_ffp      PATH  Path to the SRF or NHM file. NHM file can be obtained from                                              │
│                            https://github.com/ucgmsim/Empirical_Engine/files/15256612/NZ_FLTmodel_2010_v18p6.txt                   │
│                            [default: None]                                                                                         │
│                            [required]                                                                                              │
│ *    ll_ffp          PATH  Path to the .ll file [default: None] [required]                                                         │
│ *    vs30_ffp        PATH  Path to the .vs30 file. The file should have columns: station, vs30, (sigma) [default: None] [required] │
│ *    z_ffp           PATH  Path to the .z file that contains Z1.0 and Z2.5. The file should have columns: station, z1p0, z2p5      │
│                            [default: None]                                                                                         │
│                            [required]                                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
╭─ Options ──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ --out-dir                   PATH   output directory [default: /home/seb56/Empirical_Engine]                                        │
│ --nhm-fault-name            TEXT   Fault name to look up from NHM. Required if source-ffp is an NHM file                           │
│ --rjb-max                   FLOAT  Only calculate for stations whose rjb is below this value [default: 200]                        │
│ --install-completion               Install completion for the current shell.                                                       │
│ --show-completion                  Show completion for the current shell, to copy it or customize the installation.                │
│ --help                             Show this message and exit.                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

```
Example:

Using SRF
```
python ~/Empirical_Engine/empirical/scripts/collect_sites_info.py Srf/3460014_REL01.srf geoNet_stats+2022-06-14.ll geoNet_stats+2022-06-14.vs30 geoNet_stats+2022-06-14.z 

```
Using NHM (if no SRF is available, but it is a NHM fault)

```
 python ~/Empirical_Engine/empirical/scripts/collect_sites_info.py ./NZ_FLTmodel_2010_v18p6.txt geoNet_stats+2022-06-14.ll geoNet_stats+2022-06-14.vs30 geoNet_stats+2022-06-14.z  --nhm-fault-name Ashley

```

2024-08-04 19:58 UTC, claudio525 commented on empirical/scripts/collect_sites_info.py
> +    print(source_ffp.suffix)
debug print?

2024-08-04 19:58 UTC, claudio525 commented on empirical/scripts/collect_sites_info.py
> +    site_df = pd.concat([stations_df, vs30_df, z_df], axis=1)
If data is missing in one of these for a site, you'll end up with NaN entries, which may cause issues down the line. Might be a good idea to add a step somewhere that checks that these agree, or if not print a message and drop those sites?

2024-08-05 01:20 UTC, lispandfound requested changes

2024-08-05 01:20 UTC, lispandfound commented on empirical/scripts/calculate_empirical.py
>      srfdata_ffp: Path = None,
```suggestion
    srfdata_ffp: Optional[Path] = None,
```

2024-08-05 01:20 UTC, lispandfound commented on empirical/scripts/collect_sites_info.py
> +            file_okay=True,
I'd set `dir_okay=False` instead.

2024-08-05 01:59 UTC, AndrewRidden-Harper reviewed
Looks good to me, noting the others' feedback

2024-08-05 05:29 UTC, sungeunbae commented on empirical/scripts/calculate_empirical.py
>      srfdata_ffp: Path = None,
It is slightly complicated, as srfdata_ffp is "sort of" expected, and if it doesn't, at least we need nz_gmdb_source_ffp. 
Updated the docstring for clarification.

2024-08-05 21:56 UTC, joelridden commented on empirical/scripts/collect_sites_info.py
>              dir_okay=True,
Was meaning this more of a replacement as dir_okay is default True so isnt needed

2024-08-05 21:56 UTC, joelridden commented on empirical/scripts/calculate_empirical.py
>      srfdata_ffp: Path = None,
Even then I think it's still technically Optional because sometimes you don't need to specify it

2024-08-06 01:47 UTC, lispandfound commented on empirical/scripts/calculate_empirical.py
>      srfdata_ffp: Path = None,
@joelridden is correct. The `Optional` annotation just says "this value can be None sometimes". This is, rather unfortunately in my opinion, the [type-theory term](https://en.wikipedia.org/wiki/Option_type) for such values. If I were type-theory dictator for the day I'd probably change this to `Nullable` or `Maybe`.

2024-08-06 21:51 UTC, lispandfound approved these changes

2024-08-06 22:04 UTC, AndrewRidden-Harper approved these changes

2024-08-07 21:45 UTC, joelridden approved these changes

2024-08-07 21:46 UTC, merged