Oq
ucgmsim/Empirical_Engine pull request #49
Opened 2020-11-12 00:39 UTC by viktor76525

openquake wrapper complete
doesn't require openquake be installed, only needed if using openquake models
can pass a known model/class from list or pass any openquake model class, most likely not requiring code change unless it has new/rare parameters
tries to return all 3 standard deviations in same order as other empirical models

2020-11-25 02:59 UTC, jasonmotha requested changes
Please put the plotting scripts in a verification folder. These ones don't actually have to be part of the pip package.

2020-11-25 04:05 UTC, jasonmotha approved these changes

2020-11-26 02:02 UTC, jasonmotha commented on verification/plots.py
> +                    # but zhao expects a list?
compute_gmm should be able to take a list of periods rather than needing to pass each period individually.

2020-11-26 22:23 UTC, jasonmotha approved these changes

2020-11-26 22:37 UTC, viktor76525 commented on verification/plots.py
> +                    # but zhao expects a list?
done

2020-11-26 22:38 UTC, jasonmotha approved these changes

2020-11-26 23:51 UTC, merged