Gmpe config
ucgmsim/Empirical_Engine pull request #61
Opened 2021-07-15 22:18 UTC by shot0829

added entry for openquake config. an example/default config is also added

2021-07-15 23:08 UTC, jpa198 requested changes
Heh, that was a small enough change in the end
Only one thing though

2021-07-15 23:08 UTC, jpa198 commented on empirical/scripts/calculate_empirical.py
> +        )
This doesn't seem to change per im, so can move outside the for loop?

2021-07-15 23:22 UTC, jasonmotha reviewed
Our locally implemented models will also need to be able to support these custom configurations too. Shouldn't be too much to extend this.

Perhaps as well documenting on https://wiki.canterbury.ac.nz/display/QuakeCore/Empirical+Engine (either in an existing or current table) what parameters have options available.

2021-07-16 00:04 UTC, jpa198 approved these changes
Looks good

2021-07-16 01:45 UTC, jasonmotha approved these changes
Looks good. @shot0829 Are you able to do the documentation as to which models can accept which parameters and which values are valid?

2021-07-16 03:08 UTC, merged