Abrahamson and Kuehn 20 added, Easy to get Tom to test these as part …
ucgmsim/Empirical_Engine pull request #63
Opened 2021-08-06 04:44 UTC by jasonmotha

…of his PSHA verification

2021-08-06 04:49 UTC, SnowNooDLe approved these changes

2021-08-06 05:47 UTC, SnowNooDLe commented on requirements.txt
> +git+ssh://git@github.com:gem/oq-engine.git#egg=openquake
I think this might also work, `openquake.engine`
I had that issue saying `oq` was not found and I solved with that package.
[openquake.engine](https://pypi.org/project/openquake.engine/)

2021-08-08 20:43 UTC, jasonmotha commented on requirements.txt
> +git+ssh://git@github.com:gem/oq-engine.git#egg=openquake
This specific version needs the new API (and new empirical models) which hasn't been officially pushed as a release. 
As we use, may feed back content / updates to OQ it probably is better that we use git.

2021-08-08 22:15 UTC, SnowNooDLe commented on requirements.txt
> +git@github.com/gem/oq-engine.git#egg=openquake
Glad I remember this stuff!! (As we did have this sort of stuff in our intermediate API setup)
```bash
git+https://github.com/gem/oq-engine.git#egg=openquake
```
This would work (I just tested with your updated  code but didn't work, got this error)
`ERROR: Invalid requirement: 'git@github.com/gem/oq-engine.git#egg=openquake' (from line 1 of requirements.txt)
Hint: It looks like a path. File 'git@github.com/gem/oq-engine.git#egg=openquake' does not exist.
`
[Reference](https://pip.pypa.io/en/stable/topics/vcs-support/#git)

2021-08-09 01:50 UTC, jpa198 requested changes
Looks good

2021-08-09 01:50 UTC, jpa198 commented on empirical/util/classdef.py
> +    K_20_SS = 1092
SI codes end in 2, SS codes end in 3. Regardless of applicable tect types (See P_20)

2021-08-09 01:53 UTC, jasonmotha commented on empirical/util/classdef.py
> +    K_20_SS = 1092
I'm glad someone knows the numbering scheme...
What happens when we add another model?

2021-08-09 01:59 UTC, jpa198 approved these changes

2021-08-09 02:00 UTC, merged