Minor updates
ucgmsim/Empirical_Engine pull request #89
Opened 2022-05-12 23:16 UTC by SnowNooDLe

# Minor updates

1. CB_14 - Checked with Robin and MATLAB code maintainer at Stanford University
    - `Ztor` should not be re-estimated while `Zhyp` or `width` estimation when it's valid. Regardless of whether it's provided by a user or estimated.
    - Because we can estimate `Zhyp`, we do not have to set `Zhyp = 9.0` while estimating `width`
    - With the previous workflow, `Zhyp` will never be estimated as we always estimate `width` which leads `Zhyp` always to be 9.0
2. ZA_06
    - Maybe nothing major but hence we found that this is not the exact number, might as well change it to be slightly more accurate?
3. estimations
    - Z1.0 estimation - due to the potential overflow issue, we just use float on this.
    - determine_siteclass - Robin confirmed that those symbols needed to be changed.

2022-05-12 23:38 UTC, jasonmotha approved these changes

2022-05-12 23:57 UTC, jpa198 requested changes

2022-05-12 23:57 UTC, jpa198 commented on empirical/GMM_models/zhou_2006.py
> +    sa = np.exp(log_sa) * 1e-2 / g
1e-2 is a bit of a magic number. Should be a constant with the name m_to_cm_multiplier or similar

2022-05-12 23:57 UTC, jpa198 commented on empirical/GMM_models/CB_2014_nga.py
> +        Zhyp = d_Z + Ztor
Should only math error when Ztor >= Zbor? Should change it to an if statement so that it gets raised if something else happens

2022-05-13 00:46 UTC, SnowNooDLe commented on empirical/GMM_models/zhou_2006.py
> +    sa = np.exp(log_sa) * 1e-2 / g
Ahhhh a magic number... In that case, should we just keep 981? :thinking:

2022-05-13 00:56 UTC, SnowNooDLe commented on empirical/GMM_models/CB_2014_nga.py
> +        Zhyp = d_Z + Ztor
Just looking at some equations to get `fdZM` and `fdZD`, I don't think these will occur any errors at all.
The error will only be triggered by `math.log()`, and I guess we only had try and except ValueError to find out if we could get d_Z or not.

So I think we can even do something like

```python
try:
    d_Z = math.exp(min(fdZM + fdZD, math.log(0.9 * (Zbor - Ztor))))
except:
    # Because by hitting this block, it means we cannot get d_Z some reasons with the given equation
    # hence we just set d_Z to 0
    d_Z = 0
```

2022-05-13 01:24 UTC, SnowNooDLe commented on empirical/GMM_models/zhou_2006.py
> +    sa = np.exp(log_sa) * 1e-2 / g
then 981 is still a magic number, will just use that `m_to_cm_multiplier`
![image](https://user-images.githubusercontent.com/7849113/168192849-1f5068df-67e9-4ceb-865b-48fce7b9926e.png)
Cannot think of shortened form based on what they say in the photo.

2022-05-13 05:11 UTC, jasonmotha commented on empirical/GMM_models/zhou_2006.py
> +    sa = np.exp(log_sa) * 1e-2 / g
Sounds good. 981 v 1e-2/g are basically the same but if we've changed it; it's okay.

2022-05-13 05:18 UTC, jasonmotha commented on empirical/GMM_models/CB_2014_nga.py
> +        Zhyp = d_Z + Ztor
How's that different to above? (current commit)

I'm ambivalent mainly because coding standards in empirical models aren't great and we're planning to deprecate them anyway. 

But James is correct; an if for this is slightly nicer than the try/except.

2022-05-17 00:45 UTC, jasonmotha approved these changes

2022-05-17 00:45 UTC, jasonmotha commented on empirical/GMM_models/zhou_2006.py
> +g_unit_converter = 1e-2 / g
g_in_cm_s

2022-05-17 02:22 UTC, jasonmotha approved these changes

2022-05-17 02:26 UTC, claudio525 submitted a review, later dismissed

2022-05-20 01:34 UTC, jpa198 submitted a review, later dismissed
Just a couple of nit picks about variable naming, but otherwise good

2022-05-20 01:34 UTC, jpa198 commented on empirical/GMM_models/zhou_2006.py
> +g_in_cm_s = 1e-2 / g
Constants should be in all caps

2022-05-20 01:34 UTC, jpa198 commented on empirical/GMM_models/zhou_2006.py
> +    sa = np.exp(log_sa) * g_in_cm_s
To convert cm/2^2 you should divide by g_in_cm_s (100*g), not multiply by it, or change the name to something more accurate.
The name g_in_cm_s implies the value 981 (100*g) is contained within, not 1/(100*g)

2022-05-20 02:46 UTC, SnowNooDLe commented on empirical/GMM_models/zhou_2006.py
> +    sa = np.exp(log_sa) * g_in_cm_s
It was originally a `g_unit_converter` haha
Anything you can recommend?

2022-05-20 03:30 UTC, jpa198 commented on empirical/GMM_models/zhou_2006.py
> +    sa = np.exp(log_sa) * g_in_cm_s
Keep the name, change the value to 100\*g and then divide by it (np.exp(log_sa) / g_in_cm_s)

2022-05-20 03:42 UTC, SnowNooDLe commented on empirical/GMM_models/zhou_2006.py
> +    sa = np.exp(log_sa) * g_in_cm_s
Legend, many thanks :+1:

2022-05-20 03:45 UTC, SnowNooDLe commented on empirical/GMM_models/zhou_2006.py
> +g_in_cm_s = 1e-2 / g
I might keep this as yes, you are correct that we should set constants in all capitals, but I just realized that g and cm are units... so I thought it might be better to leave it as is.

2022-05-20 03:58 UTC, jpa198 approved these changes

2022-05-22 22:09 UTC, claudio525 approved these changes

2022-05-22 22:09 UTC, claudio525 commented on empirical/GMM_models/zhou_2006.py
> +from scipy.constants import g
import module instead of the variable?

2022-05-23 00:02 UTC, jasonmotha commented on empirical/GMM_models/zhou_2006.py
> +from scipy.constants import g
I'm happy to import g directly; g imo is one of those exceptions. (especially if you only need one constant from their file)

2022-05-25 01:30 UTC, jasonmotha approved these changes

2022-05-25 04:02 UTC, merged