Chris NZSHM
ucgmsim/Empirical_Engine pull request #97
Opened 2023-05-22 22:50 UTC by joelridden

Adding the script and needed models for the NZSHM residual calculation.
Requires oq-engine to have replaced gmsim with https://github.com/GNS-Science/OQ_NZ_SHM_GSIM_LT

2023-05-23 02:52 UTC, sungeunbae requested changes
Overall looking good  - just a few comments and questions.

2023-05-23 02:52 UTC, sungeunbae commented on empirical/scripts/nzshm_residuals.py
> +def convert_tect_class(tect_type):
Could use a dictionary?

2023-05-23 02:52 UTC, sungeunbae commented on empirical/scripts/nzshm_residuals.py
> +    with backarc_json_ffp.open("r") as f:
try-except error handling, maybe?

2023-05-23 02:52 UTC, sungeunbae commented on empirical/scripts/nzshm_residuals.py
> +    if models is None:
Why not assign DEFAULT_MODELS in the function header, such as
```
def calc_empirical(
...
   models: List[str]=DEFAULT_MODELS
   ):
```

2023-05-23 02:52 UTC, sungeunbae commented on empirical/scripts/nzshm_residuals.py
> +        model = GMM[model]
this looks a little weird to assign GMM[model] to model

2023-05-23 02:52 UTC, sungeunbae commented on empirical/scripts/nzshm_residuals.py
> +            tect_rup_df = rupture_df.copy(deep=True).loc[
Making a deep copy, then filtering? Isn't the below functionally the same?
```
tect_rup_df = rupture_df.loc[rupture_df["tect_type"] == tect_type]


```

2023-05-23 02:52 UTC, sungeunbae commented on empirical/scripts/nzshm_residuals.py
> +    residual_dir.mkdir(exist_ok=True)
parents=True, just in case

2023-05-23 21:58 UTC, joelridden commented on empirical/scripts/nzshm_residuals.py
> +    if models is None:
The reason I don't think we should do this is because of mutable arguments (https://docs.python-guide.org/writing/gotchas/) Not that it matters too much in this specific case but probably a good idea to stay away from that format to be safe.

2023-05-23 22:38 UTC, claudio525 commented on empirical/scripts/nzshm_residuals.py
> +    with backarc_json_ffp.open("r") as f:
In case the file is not found? It'll give an appropriate exception by default?

2023-05-24 03:43 UTC, claudio525 approved these changes

2023-05-24 21:42 UTC, sungeunbae approved these changes

2023-05-24 21:47 UTC, merged